name: release

on:
  push:
    tags:
      - "v*"

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Docker build and publish
        run: |
          TAG=$(echo $GITHUB_REF | grep -o "[0-9][\.].*")
          echo Imag tag is: $TAG
          docker login --username ${{ secrets.}}
      - name: Setup docker buildx
        uses: docker/setup-buildx-action@v1
      - name: Login to GitHub Container Registry
        uses: docker/login-action@v1
        with:
          registry: ghcr.io
          username: ${{ github.repository_owner }}
          password: ${{ secrets.CR_PAT }}
      - name: Get the version
        id: get_version
        run: echo ::set-output name=VERSION::${GITHUB_REF/refs\/tags\//}
      - name: Build and push Wee Dev Test
        uses: docker/build-push-action@v2
        with:
          push: true
          context: .
          file: .Dockerfile
          tags: |
            wee-dev/${{ env.USERS_IMAGE_NAME }}:${{ steps.get_version.outputs.VERSION }}
            ghcr.io/wee-dev/${{ env.USERS_IMAGE_NAME }}:${{ steps.get_version.outputs.VERSION }}
          build-args:
            - BUILD_VERSION=${{get_version.VERSION}}
      
