name: release

on:
  push:
    tags:
      - "v*"

env:
  REGISTRY: ghcr.io
  IMAGE_NAME: ${{ github.repository }}

jobs:
  build-and-push-image:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      packages: write

    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Log in to the Container registry
        uses: docker/login-action@f054a8b539a109f9f41c372932f1ae047eff08c9
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.CR_PAT }}

      - name: Extract metadata (tags, labels) for Docker
        id: meta
        uses: docker/metadata-action@98669ae865ea3cffbcbaa878cf57c20bbf1c6c38
        with:
          images: ghcr.io/${{ env.IMAGE_NAME }}

      - name: Build and push Docker image
        uses: docker/build-push-action@ad44023a93711e3deb337508980b4b5e9bcdc5dc
        with:
          context: .
          push: true
          tags: ${{ steps.meta.outputs.tags }}
          labels: ${{ steps.meta.outputs.labels }}
          build-args: |
            BUILD_VERSION=${{get_version.VERSION}}

# jobs:
#   build:
#     runs-on: ubuntu-latest
#     steps:
#       - name: Checkout
#         uses: actions/checkout@v2
#       - name: Docker build and publish
#         run: |
#           TAG=$(echo $GITHUB_REF | grep -o "[0-9][\.].*")
#           echo Imag tag is: $TAG
#           docker login --username ${{ secrets.}}
#       - name: Setup docker buildx
#         uses: docker/setup-buildx-action@v1
#       - name: Login to GitHub Container Registry
#         uses: docker/login-action@v1
#         with:
#           registry: ghcr.io
#           username: ${{ github.repository_owner }}
#           password: ${{ secrets.CR_PAT }}
#       - name: Get the version
#         id: get_version
#         run: echo ::set-output name=VERSION::${GITHUB_REF/refs\/tags\//}
#       - name: Build and push Wee Dev Test
#         uses: docker/build-push-action@v2
#         with:
#           push: true
#           context: .
#           file: .Dockerfile
#           tags: |
#             wee-dev/${{ env.USERS_IMAGE_NAME }}:${{ steps.get_version.outputs.VERSION }}
#             ghcr.io/wee-dev/${{ env.USERS_IMAGE_NAME }}:${{ steps.get_version.outputs.VERSION }}
#           build-args:
#             - BUILD_VERSION=${{get_version.VERSION}}
      
